version: '3.7'
name: slim-vue-dev

networks:
  slim-vue-internal:
    driver: bridge
  slim-vue-external:
    driver: bridge

services:
  php:
    container_name: slim-php
    build:
      args:
        user: husam
        uid: 1000
      context: ../api
      dockerfile: ../docker/php/DockerFile.dev
    restart: unless-stopped
    environment:
      - SLIM_ENV=dev
      - JWT_SECRET=${JWT_SECRET:-secret}
      - POSTGRES_VERSION=${POSTGRES_VERSION}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@slim-postgres:5432/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION}&charset=utf8
    volumes:
      - ./../api:/app
    networks:
      - slim-vue-internal

  database:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: slim-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      - slim-vue-internal

  nginx:
    image: nginx:alpine
    container_name: slim-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./../api:/app
      - ./../docker/nginx/dev:/etc/nginx/conf.d
    networks:
      - slim-vue-external
      - slim-vue-internal

  node:
    image: node:lts-bullseye
    container_name: vue-node
    environment:
      NODE_ENV: dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./../frontend:/usr/app
    working_dir: /usr/app
    entrypoint: >
      bash -c "npm install && npm run dev"
    networks:
      - slim-vue-external
