name: API Tests

on: [pull_request]

env:
  JWT_SECRET: friendship

jobs:
  tests:
    name: Tests PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.1]
        experimental: [false]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          working-directory: ./api

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          working-directory: ./api

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2
        with:
          working-directory: ./api

      - name: Coding standards
        if: matrix.analysis
        working-directory: ./api
        run: vendor/bin/phpcs

      - name: Static analysis
        if: matrix.analysis
        working-directory: ./api
        run: vendor/bin/phpstan

      - name: Tests
        working-directory: ./api
        run: vendor/bin/phpunit --coverage-clover clover.xml
